/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainPage;

import Login.TaiKhoan;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author User
 */
public class frmTrangChu extends javax.swing.JFrame {

    private TaiKhoan taiKhoan;
    public frmTrangChu(TaiKhoan tk) {
        this.taiKhoan = tk; // Gán thông tin tài khoản
        initComponents(); // Khởi tạo các thành phần
        // Có thể sử dụng thông tin từ tk để hiển thị trong form
    }
    public frmTrangChu() {
        initComponents();
        init();
        ChuyenManHinhController controller = new ChuyenManHinhController(PanelView);
        controller.setView(jpTrangChu, jlTrangChu);
        List<DanhMucBean> listItem = new ArrayList<>();
        listItem.add(new DanhMucBean("TrangChu",jpTrangChu,jlTrangChu));
        listItem.add(new DanhMucBean("KhacHang",jpQLKH,JLKhachHang));
        listItem.add(new DanhMucBean("SanPham",jpQLSanPham,JLSanPham));
        listItem.add(new DanhMucBean("DanhMuc",jpQLDanhMuc,JLDanhMuc));
        listItem.add(new DanhMucBean("CuaHang",jpQLCuaHang,JLCuaHang));
        listItem.add(new DanhMucBean("HoaDon",jpQLHoaDon,JLHoaDon));
        listItem.add(new DanhMucBean("DiaDiem",jpQLDiaDiem,JLDiaDiem));
        controller.setEvent(listItem);
    }
    private void init(){
        setBackground(new Color(0,0,0,0));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelBoderFrm1 = new PanelBoder.PanelBoderFrm();
        jpQLKH = new javax.swing.JPanel();
        JLKhachHang = new javax.swing.JLabel();
        jpQLSanPham = new javax.swing.JPanel();
        JLSanPham = new javax.swing.JLabel();
        jpQLDanhMuc = new javax.swing.JPanel();
        JLDanhMuc = new javax.swing.JLabel();
        jpQLCuaHang = new javax.swing.JPanel();
        JLCuaHang = new javax.swing.JLabel();
        jpQLHoaDon = new javax.swing.JPanel();
        JLHoaDon = new javax.swing.JLabel();
        jpQLDiaDiem = new javax.swing.JPanel();
        JLDiaDiem = new javax.swing.JLabel();
        panelBoderFrm4 = new PanelBoder.PanelBoderFrm();
        JLExit = new javax.swing.JLabel();
        jpTrangChu = new javax.swing.JPanel();
        jlTrangChu = new javax.swing.JLabel();
        PanelView = new PanelBoder.PanelBoderFrm();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1700, 1200));
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1700, 1000));

        panelBoderFrm1.setBackground(new java.awt.Color(255, 255, 153));

        jpQLKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpQLKHMouseClicked(evt);
            }
        });

        JLKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        JLKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLKhachHang.setText("QUẢN LÝ KHÁCH HÀNG");

        javax.swing.GroupLayout jpQLKHLayout = new javax.swing.GroupLayout(jpQLKH);
        jpQLKH.setLayout(jpQLKHLayout);
        jpQLKHLayout.setHorizontalGroup(
            jpQLKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpQLKHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpQLKHLayout.setVerticalGroup(
            jpQLKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpQLKHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpQLSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpQLSanPhamMouseClicked(evt);
            }
        });

        JLSanPham.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        JLSanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLSanPham.setText("QUAN LÝ SẢN PHẨM");

        javax.swing.GroupLayout jpQLSanPhamLayout = new javax.swing.GroupLayout(jpQLSanPham);
        jpQLSanPham.setLayout(jpQLSanPhamLayout);
        jpQLSanPhamLayout.setHorizontalGroup(
            jpQLSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpQLSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpQLSanPhamLayout.setVerticalGroup(
            jpQLSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpQLSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpQLDanhMuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpQLDanhMucMouseClicked(evt);
            }
        });

        JLDanhMuc.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        JLDanhMuc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLDanhMuc.setText("QUẢN LÝ DANH MỤC");

        javax.swing.GroupLayout jpQLDanhMucLayout = new javax.swing.GroupLayout(jpQLDanhMuc);
        jpQLDanhMuc.setLayout(jpQLDanhMucLayout);
        jpQLDanhMucLayout.setHorizontalGroup(
            jpQLDanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpQLDanhMucLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLDanhMuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpQLDanhMucLayout.setVerticalGroup(
            jpQLDanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpQLDanhMucLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLDanhMuc, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpQLCuaHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpQLCuaHangMouseClicked(evt);
            }
        });

        JLCuaHang.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        JLCuaHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLCuaHang.setText("QUẢN LÝ CỬA HÀNG");

        javax.swing.GroupLayout jpQLCuaHangLayout = new javax.swing.GroupLayout(jpQLCuaHang);
        jpQLCuaHang.setLayout(jpQLCuaHangLayout);
        jpQLCuaHangLayout.setHorizontalGroup(
            jpQLCuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpQLCuaHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLCuaHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpQLCuaHangLayout.setVerticalGroup(
            jpQLCuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpQLCuaHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLCuaHang, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpQLHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpQLHoaDonMouseClicked(evt);
            }
        });

        JLHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        JLHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLHoaDon.setText("QUẢN LÝ HÓA ĐƠN");

        javax.swing.GroupLayout jpQLHoaDonLayout = new javax.swing.GroupLayout(jpQLHoaDon);
        jpQLHoaDon.setLayout(jpQLHoaDonLayout);
        jpQLHoaDonLayout.setHorizontalGroup(
            jpQLHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpQLHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpQLHoaDonLayout.setVerticalGroup(
            jpQLHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpQLHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpQLDiaDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpQLDiaDiemMouseClicked(evt);
            }
        });

        JLDiaDiem.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        JLDiaDiem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLDiaDiem.setText("QUẢN LÝ ĐỊA ĐIỂM");

        javax.swing.GroupLayout jpQLDiaDiemLayout = new javax.swing.GroupLayout(jpQLDiaDiem);
        jpQLDiaDiem.setLayout(jpQLDiaDiemLayout);
        jpQLDiaDiemLayout.setHorizontalGroup(
            jpQLDiaDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpQLDiaDiemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLDiaDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpQLDiaDiemLayout.setVerticalGroup(
            jpQLDiaDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpQLDiaDiemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLDiaDiem, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBoderFrm4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBoderFrm4MouseClicked(evt);
            }
        });

        JLExit.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        JLExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLExit.setText("ĐĂNG XUẤT");

        javax.swing.GroupLayout panelBoderFrm4Layout = new javax.swing.GroupLayout(panelBoderFrm4);
        panelBoderFrm4.setLayout(panelBoderFrm4Layout);
        panelBoderFrm4Layout.setHorizontalGroup(
            panelBoderFrm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBoderFrm4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLExit, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBoderFrm4Layout.setVerticalGroup(
            panelBoderFrm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBoderFrm4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLExit, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        jlTrangChu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jlTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTrangChu.setText("TRANG CHỦ");

        javax.swing.GroupLayout jpTrangChuLayout = new javax.swing.GroupLayout(jpTrangChu);
        jpTrangChu.setLayout(jpTrangChuLayout);
        jpTrangChuLayout.setHorizontalGroup(
            jpTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTrangChuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpTrangChuLayout.setVerticalGroup(
            jpTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTrangChuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelBoderFrm1Layout = new javax.swing.GroupLayout(panelBoderFrm1);
        panelBoderFrm1.setLayout(panelBoderFrm1Layout);
        panelBoderFrm1Layout.setHorizontalGroup(
            panelBoderFrm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpQLKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpQLSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpQLDanhMuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpQLCuaHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpQLHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpQLDiaDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBoderFrm1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(panelBoderFrm4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        panelBoderFrm1Layout.setVerticalGroup(
            panelBoderFrm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBoderFrm1Layout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addComponent(jpTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpQLKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpQLSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpQLDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpQLCuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpQLHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpQLDiaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(panelBoderFrm4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout PanelViewLayout = new javax.swing.GroupLayout(PanelView);
        PanelView.setLayout(PanelViewLayout);
        PanelViewLayout.setHorizontalGroup(
            PanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        PanelViewLayout.setVerticalGroup(
            PanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBoderFrm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBoderFrm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1280, 784));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jpQLKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpQLKHMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jpQLKHMouseClicked

    private void jpQLSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpQLSanPhamMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jpQLSanPhamMouseClicked

    private void jpQLDanhMucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpQLDanhMucMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jpQLDanhMucMouseClicked

    private void jpQLCuaHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpQLCuaHangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jpQLCuaHangMouseClicked

    private void jpQLHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpQLHoaDonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jpQLHoaDonMouseClicked

    private void jpQLDiaDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpQLDiaDiemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jpQLDiaDiemMouseClicked

    private void panelBoderFrm4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBoderFrm4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelBoderFrm4MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLCuaHang;
    private javax.swing.JLabel JLDanhMuc;
    private javax.swing.JLabel JLDiaDiem;
    private javax.swing.JLabel JLExit;
    private javax.swing.JLabel JLHoaDon;
    private javax.swing.JLabel JLKhachHang;
    private javax.swing.JLabel JLSanPham;
    private PanelBoder.PanelBoderFrm PanelView;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jlTrangChu;
    private javax.swing.JPanel jpQLCuaHang;
    private javax.swing.JPanel jpQLDanhMuc;
    private javax.swing.JPanel jpQLDiaDiem;
    private javax.swing.JPanel jpQLHoaDon;
    private javax.swing.JPanel jpQLKH;
    private javax.swing.JPanel jpQLSanPham;
    private javax.swing.JPanel jpTrangChu;
    private PanelBoder.PanelBoderFrm panelBoderFrm1;
    private PanelBoder.PanelBoderFrm panelBoderFrm4;
    // End of variables declaration//GEN-END:variables
}
